name: 📚 Documentation Update
description: Report an issue in the project's documentation or README.md file.
title: "[Doc Update]: "

body:
  - type: checkboxes
    attributes:
      label: "Is there an existing issue for this?"
      description: "Please search to see if an issue already exists for the bug you encountered."
      options:
        - label: "I have searched the existing issues"
          required: true
  - type: textarea
    id: documentation-bug-description
    attributes:
      label: "Issue Description ✍️"
      description: Enter a brief description about the documentation issue
      placeholder: Please include a summary, also include relevant motivation and context.
      value: |
        ## 📌 Issue Summary  
        <!-- Provide a brief summary of the issue --> 

        ## 📷 Screenshot  
        <!-- Attach screenshots if applicable -->

        ## 💡 Suggestions  
        <!-- Any ideas for a fix? -->
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Record"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I want to work on this issue"
          required: false
